version: '3.8'
services:
  evaluacion3-app:
    build: .
    image: evaluacion3-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/mongoContainer
    ports:
      - '8081:8080'
    depends_on:
      - mongodb
    volumes:
      - .:/src

  mongodb:
    image: mongo:latest
    ports:
      - '2412:27017'
    volumes:
      - dbdata6:/data/db

volumes:
  dbdata6:

    
